spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #애플리케이션 실행시점에 테이블 새로 생성됨
    properties:
      hibernate:
#        show_sql: true  #system.out.println을 통해서 출력됨
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #로거를 이용해서 sql이 출력됨